[package]
name = "tauri-plugin-test"
version = "0.0.0"
authors = [ "ahriknow" ]
description = "plugin of ahridbms for test"
edition = "2021"
rust-version = "1.57"

[dependencies]
tauri = { version = "1.0.5" }
